//Test
export const TEST = 'TEST'
export const test = () => ({ type: TEST })

export const TEST_SUCCESS = 'TEST_SUCCESS'
export const testSuccess = () => ({ type: TEST_SUCCESS, payload: 'test success' })

//USER
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'

export const USER_GET_USER = 'USER_GET_USER'
export const USER_SET_USER = 'USER_SET_USER'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_SAVE_PROFILE = 'USER_SAVE_PROFILE'
export const USER_SAVE_PROFILE_SUCCESS = 'USER_SAVE_PROFILE_SUCCESS'
export const USER_SAVE_PROFILE_FAILED = 'USER_SAVE_PROFILE_FAILED'

export const USER_REGISTER = 'USER_REGISTER'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED'

export const USER_DELETE = 'USER_DELETE'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAILED = 'USER_DELETE_FAILED'

//TOKEN
export const GET_TOKEN = 'GET_TOKEN'

//ABONNEMENT
export const ABONNEMENT_REGISTER = 'ABONNEMENT_REGISTER'
export const ABONNEMENT_REGISTER_SUCCEESS = 'ABONNEMENT_REGISTER_SUCCEESS'
export const ABONNEMENT_REGISTER_FAILED = 'ABONNEMENT_REGISTER_FAILED'

